### ISSUE TITLE
Admin page toggle values display incorrect value

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#27]
The values displayed on the admin page for the toggle functions are unreliable. For example, clicking the "Switch Site Mode"or "Switch DB's" button does change the value of the underlying value, but the value displayed is unchanged until the page is refreshed. This happens pretty reliably on Tom's machine.

The "Editing Allowed" button suffers from what looks to be a similar issue. Clicking it results in the expected toggle of the underlying value and the displayed value. However, refreshing the page immediately after clicking the button results in the display showing the untoggled value. Refreshing the page again results in the correct toggled value being displayed.

Fails in version: All / 4cfc4ec
Fails on Host: Tom's machine
Fails with Browser: Chrome

**Comment by krcowles** [comment]
Does this same behavior also occur on main (or a test site) when using your machine, or only with localhost on your machine?

**Comment by tjsandberg** [comment]
I only see it on localhost on my machine.

**Comment by tjsandberg** [comment]
I tried walking through the code that does the DB switch but got thoroughly confused. If you want to debug some time on a Hangouts, let me know.

**Comment by krcowles** [comment]
I just dsicovered that my VSC crashed and won’t open, probably because of the mad stumbling effort to restore my drive. Because it failed a couple of times, there are three disks mounted with the same name. I’m trying renaming the ones I ‘think’ are failed versions, so that first of all, my backup drive will back up! It doesn’t know which disk to use… I’m trying to sort this all out, but yes, eventually, we can do a hangouts. If I have to reload VSC, it’s a small nightmare restoring the settings and PHP sniffer stuff I put in place.

**Comment by krcowles** [comment]
Downloaded new copy of VSC and somehow all the settings automagically transferred - anyways, I am trying a whole new paradigm for the suspect admintools buttons (limited to 'Switch Site Mode' **only** right now). If this helps, I can implement it more broadly. Just pushed.

**Comment by tjsandberg** [comment]
It doesn't seem to make any difference. Still seeing the same behavior. I did a fetch, pull, and cleared cache.

**Comment by krcowles** [comment]
OK - one last 'hare-brained' attempt. This one has a confirmation alert box - it may or may not help. Again, it's only applied to the 'Switch Site Mode' button. After you hit the 'OK' button, the page will refresh. Just pushed, let me know. I inadvertently left the mode in 'Production'

**Comment by tjsandberg** [comment]
It works if I am relatively slow to click the OK button on the alert. If I quickly click OK, the problem is not fixed.

**Comment by krcowles** [comment]
Thanks for bearing with me. It all points to the 'self-modifying code' issues. I am going to scrub the current approach and do something that doesn't change any file contents. I'll notify you when ready - it may be a while.

**Comment by krcowles** [comment]
Somehow it seems that each site ('main', test site[s]) must store the current settings *somewhere* in order to be accessed when visiting the site.  Up to now, that has been in a local settings file. Since the changed settings in the local file seem to take awhile to be 'seen' on your machine, one alternative is to use a database table which stores 'sites' [urls or a portion thereof] and their corresponding settings. Then the site's settings can be accessed in the global boot file and implemented for the site. Does this seem reasonable?

**Comment by tjsandberg** [comment]
It might work, but I think there are some devils in the details. For example, would the new table be saved in the sql database file when we do Export All Tables? And how would we get rid of obsolete entries in the new table?

It also just bothers me that we have been unable to understand why the problem happens on my machine with the current implementation. Is it a race condition, a caching issue, or something else?

**Comment by krcowles** [comment]
I understand your frustration - we have spent some time on this one! I remember looking at file write times, and they all looked to be as expected. I don't think we played much with caching though, so I found an online article talking about how to disable cache for a directory. Since we already have an admin/.htaccess file, it is a simple addition of a few lines of code. I just pushed 'adminNoCache' and wondered if you would be willing to try that one. It's very puzzling, because while the tools page is requested via url and appears in the headers, any 'required' files do not appear in the headers - so I don't know if 'fresh' copies are being extracted. I couldn't find anything on line about how include/require files are accessed by the server (with respect to caching).

**Comment by tjsandberg** [comment]
It was a good idea, but I'm still seeing the same behavior on my machine. After clicking "Switch Site Mode", "Switch DB's", or "Editing Allowed", I have to manually refresh the page once or twice before the correct state value is displayed.

**Comment by krcowles** [comment]
The approach to alter the production/development environment and/or change between test and main databases has been modified in the master commit a9bfeba and the issue no longer exists.
